---
name: Compile

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - 'master'
      - '*dev*'
    paths-ignore:
      - '*.md'
      - '.git*'
  push:
    branches:
      - 'master'
      - '*dev*'
    paths-ignore:
      - '*.md'
      - '.git*'
  workflow_call:

env:
  # Setting an environment variable with the value of a configuration variable.
  INDI_COMMON_WORKDIR: ${{ vars.INDI_COMMON_WORKDIR || 'indicators-common' }}

jobs:
  mt4:
    name: Installs platform (4)
    uses: EA31337/EA-Tester/.github/workflows/platform-linux.yml@dev
    with:
      artifact_name: mt4
      artifact_overwrite: true
      version: 4
  mt5:
    name: Installs platform (5)
    uses: EA31337/EA-Tester/.github/workflows/platform-linux.yml@dev
    with:
      artifact_name: mt5
      artifact_overwrite: true
      version: 5

  compile-platform-indicators:
    defaults:
      run:
        shell: powershell
    name: Compile platform indicators
    needs: [mt4, mt5]
    runs-on: windows-latest
    strategy:
      matrix:
        version: [4, 5]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mt${{ matrix.version }}
          path: .mt${{ matrix.version }}
      - name: Compile MQL
        uses: fx31337/mql-compile-action@dev
        with:
          include: .
          init-platform: true
          mt-path: .mt${{ matrix.version }}
          path: .mt${{ matrix.version }}/**/MQL?/Indicators
          verbose: true
      - name: Copy MQL to the current location
        run: Copy-Item -Path ".mt?\*\*\MQL?" -Destination . -Recurse -Verbose
      - name: List all source code files
        run: '(Get-ChildItem -Recurse -Path "MQL?" -Include *.mq[45]).fullname'
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path "MQL?" -Include *.ex[45]).fullname'
      - name: Upload platform indicators
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: platform-indicators-mql${{ matrix.version }}
          path: MQL?/**/*.[me][qx][45h]
      - if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
    timeout-minutes: 20

  compile-indicators:
    defaults:
      run:
        shell: powershell
    name: Compile indicators
    needs: [compile-platform-indicators]
    runs-on: windows-latest
    strategy:
      matrix:
        version: [4, 5]
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.INDI_COMMON_WORKDIR }}
          ref: ${{ github.head_ref || github.ref_name }}
          repository: EA31337/EA31337-indicators-common
      - uses: actions/checkout@v3
        with:
          path: MQL4/Include/EA31337-classes
          ref: v3.000.1
          repository: EA31337/EA31337-classes
      - uses: actions/checkout@v3
        with:
          path: MQL5/Include/EA31337-classes
          ref: v3.000.1
          repository: EA31337/EA31337-classes
      - uses: actions/download-artifact@v4
        with:
          name: mt${{ matrix.version }}
          path: .mt${{ matrix.version }}
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: platform-indicators-mql?
      - name: List all source code files
        run: '(Get-ChildItem -Recurse -Path . -Include *.mq[45]).fullname'
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - name: Compile
        uses: fx31337/mql-compile-action@master
        with:
          include: MQL5
          mt-path: .mt${{ matrix.version }}
          path: ${{ env.INDI_COMMON_WORKDIR }}/**/*.mt5.mq${{ matrix.version }}
          # yamllint disable-line rule:line-length
          path-ignore: '**/{AC,AD,ADX,ADXW,Alligator,AO,Bears,Bulls,BB,BWMFI,CCI,CHO,CHV,DeMarker,DEMA,DPO,Envelopes,Force,FrAMA,Gator,MACD,MFI,MI,OsMA,RSI,StdDev,TEMA,TRIX,UOS}.{mt?.mq?,mq?}'
          verbose: true
      - name: Compile
        uses: fx31337/mql-compile-action@master
        with:
          include: MQL${{ matrix.version }}
          mt-path: .mt${{ matrix.version }}
          path: ${{ env.INDI_COMMON_WORKDIR }}/**/*.mq${{ matrix.version }}
          # yamllint disable-line rule:line-length
          path-ignore: '**/{AC,AD,ADX,ADXW,Alligator,AMA,AO,ASI,ATR,Bears,Bulls,BB,BWMFI,CCI,CHO,CHV,DeMarker,DEMA,DPO,Envelopes,Force,Fractals,FrAMA,Gator,HeikenAshi,Ichimoku,MACD,MA,MI,MFI,MOM,OBV,OsMA,PriceChannel,PVT,ROC,RSI,RVI,SAR,StdDev,Stochastic,TEMA,TRIX,UOS,VIDYA,VROC,Volumes,WAD,WPR,ZigZag}.{mt?.mq?,mq?}'
          # path-ignore: '**/{Foo,{tests,Examples,Experts,Scripts}/**/*}.mq?'
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
      - name: Upload indicator artifacts
        uses: actions/upload-artifact@v3
        with:
          name: indicators-common
          path: ${{ env.INDI_COMMON_WORKDIR }}/**/*.ex[45]
    timeout-minutes: 30

  cleanup:
    name: Clean-up
    needs: [compile-indicators]
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: mt?
