---
name: Compile MQL

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - 'master'
      - '*dev*'
    paths-ignore:
      - '*.md'
      - '.git*'
  push:
    branches:
      - 'master'
      - '*dev*'
    paths-ignore:
      - '*.md'
      - '.git*'

jobs:
  GetList:
    outputs:
      filelist: ${{ env.filelist }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set output with list of files
        run: |
          import glob, json, os
          files = json.dumps(glob.glob("Oscillator/*.mq?"))
          with open(os.getenv('GITHUB_ENV'), "a") as file:
            file.write(f"filelist={files}\n")
        shell: python
      - name: Display output
        run: echo ${{ env.filelist }}

  Compile-Indicators-Platform:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    steps:
      - name: Compile (build 1382)
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          init-platform: true
          mt-version: 4.0.0.1382.2
          path: Indicators
          verbose: true
      - name: Upload MQL4 indicators
        uses: actions/upload-artifact@v3
        with:
          name: Indicators-platform
          path: ${{ env.MT4_PATH }}/MQL?/**/*.[me][qx][45h]
      - name: Compile (build 2361)
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          init-platform: true
          mt-version: 5.0.0.2361
          path: .platform/**/MQL?/Indicators
          verbose: true
      - name: Upload MQL5 indicators
        uses: actions/upload-artifact@v3
        with:
          name: Indicators-platform
          path: ${{ env.MT5_PATH }}/MQL?/**/*.[me][qx][45h]
      - name: Compile (build 3815)
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          init-platform: true
          mt-version: 5.0.0.3815
          path: .platform/**/MQL?/Indicators
          verbose: true
      - name: Upload MQL5 indicators
        uses: actions/upload-artifact@v3
        with:
          name: Indicators-platform
          path: ${{ env.MT5_PATH }}/MQL?/**/*.[me][qx][45h]
      - name: List all source code files
        run: '(Get-ChildItem -Recurse -Path . -Include *.mq[45]).fullname'
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
    timeout-minutes: 20

  Compile-Indicators:
    defaults:
      run:
        shell: powershell
    needs: [GetList, Compile-Indicators-Platform]
    runs-on: windows-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.GetList.outputs.filelist) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          path: MQL4/Include/EA31337-classes
          ref: v2.012.1
          repository: EA31337/EA31337-classes
      - uses: actions/checkout@v3
        with:
          path: MQL5/Include/EA31337-classes
          ref: v2.012.1
          repository: EA31337/EA31337-classes
      - uses: actions/download-artifact@v3
        with:
          name: Indicators-platform
      - name: List all source code files
        run: '(Get-ChildItem -Recurse -Path . -Include *.mq[45]).fullname'
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - name: Compile (build 1382)
        if: endsWith(matrix.file, '.mq4')
        uses: fx31337/mql-compile-action@master
        with:
          include: MQL4
          init-platform: true
          mt-version: 4.0.0.1382
          path: ${{ matrix.file }}
          verbose: true
      - name: Compile (build 2361)
        uses: fx31337/mql-compile-action@master
        with:
          include: MQL5
          init-platform: true
          mt-version: 5.0.0.2361
          path: ${{ matrix.file }}
          verbose: true
      - name: Compile (build 2515)
        if: endsWith(matrix.file, '.mq5')
        uses: fx31337/mql-compile-action@master
        with:
          include: MQL5
          init-platform: true
          mt-version: 5.0.0.2515
          path: ${{ matrix.file }}
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
      - name: Upload indicator artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Indicators-common
          path: '**/*.ex[45]'
    timeout-minutes: 10
