---
name: Compile

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - 'master'
      - 'dev*'
    paths-ignore:
      - '*.md'
      - '.git*'
  push:
    branches:
      - 'master'
      - 'dev*'
    paths-ignore:
      - '*.md'
      - '.git*'

jobs:
  GetList:
    outputs:
      filelist: ${{ steps.get-files.outputs.filelist }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output with list of files
        id: get-files
        run: |
          import glob, json, os
          files = glob.glob("**/*.mq?")
          print("::set-output name=filelist::{}".format(json.dumps(files)))
        shell: python
      - name: Display output
        run: echo ${{ steps.get-files.outputs.filelist }}
  Compile:
    defaults:
      run:
        shell: powershell
    needs: [GetList]
    runs-on: windows-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.GetList.outputs.filelist) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: Include/EA31337-classes
          ref: dev
          repository: EA31337/EA31337-classes
      - name: Compile (build 2361)
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          init-platform: true
          mt-version: 5.0.0.2361
          path: ${{ matrix.file }}
          verbose: true
      - name: Compile (build 2515)
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          init-platform: true
          mt-version: 5.0.0.2515
          path: ${{ matrix.file }}
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
      - name: Upload indicator artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Indicators-other
          path: '**/*.ex?'
